export const types = {
  REQUEST_GAMES: 'REQUEST_GAMES',
  RECEIVE_GAMES: 'RECEIVE_GAMES',
  REQUEST_GAME: 'REQUEST_GAME',
  RECEIVE_GAME: 'RECEIVE_GAME',
  SET_FRAME: 'SET_FRAME',
  SET_ZOOM: 'SET_ZOOM',
}
